# Generated by Django 5.1.4 on 2026-05-14 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewer_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="profiles.engineerprofile",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profile_views",
                "indexes": [
                    models.Index(
                        fields=["engineer", "viewed_at"],
                        name="profile_vie_enginee_0edd29_idx",
                    )
                ],
            },
        ),
    ]
