# Generated by Django 5.1.4 on 2026-05-14 11:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("avatar", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "client_profiles",
            },
        ),
        migrations.CreateModel(
            name="EngineerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("civil", "Civil Engineering"),
                            ("structural", "Structural Engineering"),
                            ("mechanical", "Mechanical Engineering"),
                            ("electrical", "Electrical Engineering"),
                            ("quantity_surveyor", "Quantity Surveying"),
                            ("architect", "Architecture"),
                            ("geotechnical", "Geotechnical Engineering"),
                            ("environmental", "Environmental Engineering"),
                            ("project_manager", "Project Management"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField()),
                ("years_exp", models.PositiveSmallIntegerField(default=0)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_country", models.CharField(blank=True, max_length=100)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lng", models.FloatField(blank=True, null=True)),
                ("avatar", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("profile_views", models.PositiveIntegerField(default=0)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "engineer_profiles",
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=200)),
                ("issued_on", models.DateField()),
                ("expires", models.DateField(blank=True, null=True)),
                ("document", models.URLField(blank=True)),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="profiles.engineerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "certifications",
            },
        ),
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("completed", models.DateField()),
                ("cover_image", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="profiles.engineerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_projects",
                "ordering": ["-completed"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="profiles.portfolioproject",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_media",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SavedEngineer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_engineers",
                        to="profiles.clientprofile",
                    ),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.engineerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "saved_engineers",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="profiles.engineerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "skills",
            },
        ),
        migrations.AddIndex(
            model_name="engineerprofile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="engineer_pr_search__637c52_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="engineerprofile",
            index=models.Index(
                fields=["location_lat", "location_lng"],
                name="engineer_pr_locatio_70f844_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="engineerprofile",
            index=models.Index(
                fields=["avg_rating"], name="engineer_pr_avg_rat_4b2e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engineerprofile",
            index=models.Index(
                fields=["specialization"], name="engineer_pr_special_8d3093_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engineerprofile",
            index=models.Index(
                fields=["availability"], name="engineer_pr_availab_8d9e21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioproject",
            index=models.Index(
                fields=["engineer", "completed"], name="portfolio_p_enginee_78d98f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedengineer",
            unique_together={("client", "engineer")},
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("engineer", "name")},
        ),
    ]
